-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 10:24:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownicy` (
  `idPracownicy` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Imię` VARCHAR(45) NOT NULL,
  `PESEL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPracownicy`),
  UNIQUE INDEX `PESEL_UNIQUE` (`PESEL` ASC) VISIBLE,
  UNIQUE INDEX `idPracownicy_UNIQUE` (`idPracownicy` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wydarzenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wydarzenia` (
  `idWydarzenia` INT NOT NULL AUTO_INCREMENT,
  `idPracownicy` INT NOT NULL,
  `idEksponaty` INT NOT NULL,
  `idSale` INT NOT NULL,
  `Nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idWydarzenia`),
  UNIQUE INDEX `idWydarzenia_UNIQUE` (`idWydarzenia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eksponaty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eksponaty` (
  `idEksponaty` INT NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  `DataProdukcji` DATE NULL,
  `MiejscePochodzenia` VARCHAR(45) NULL,
  `StanEksponatu` VARCHAR(45) NULL,
  `CzyZarezerwowany` TINYINT NOT NULL,
  `DataCzynnościKonserwatorskich` DATE NOT NULL,
  `Wydarzenia_idWydarzenia` INT NOT NULL,
  PRIMARY KEY (`idEksponaty`, `Wydarzenia_idWydarzenia`),
  UNIQUE INDEX `idEksponaty_UNIQUE` (`idEksponaty` ASC) VISIBLE,
  INDEX `fk_Eksponaty_Wydarzenia1_idx` (`Wydarzenia_idWydarzenia` ASC) VISIBLE,
  CONSTRAINT `fk_Eksponaty_Wydarzenia1`
    FOREIGN KEY (`Wydarzenia_idWydarzenia`)
    REFERENCES `mydb`.`Wydarzenia` (`idWydarzenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `idSale` INT NOT NULL AUTO_INCREMENT,
  `Rozmiar` INT NOT NULL,
  `Wydarzenia_idWydarzenia` INT NOT NULL,
  PRIMARY KEY (`idSale`, `Wydarzenia_idWydarzenia`),
  UNIQUE INDEX `idSale_UNIQUE` (`idSale` ASC) VISIBLE,
  INDEX `fk_Sale_Wydarzenia1_idx` (`Wydarzenia_idWydarzenia` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Wydarzenia1`
    FOREIGN KEY (`Wydarzenia_idWydarzenia`)
    REFERENCES `mydb`.`Wydarzenia` (`idWydarzenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wydarzenia_has_Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wydarzenia_has_Pracownicy` (
  `Wydarzenia_idWydarzenia` INT NOT NULL,
  `Pracownicy_idPracownicy` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Wydarzenia_idWydarzenia`, `Pracownicy_idPracownicy`),
  INDEX `fk_Wydarzenia_has_Pracownicy_Pracownicy1_idx` (`Pracownicy_idPracownicy` ASC) VISIBLE,
  INDEX `fk_Wydarzenia_has_Pracownicy_Wydarzenia_idx` (`Wydarzenia_idWydarzenia` ASC) VISIBLE,
  CONSTRAINT `fk_Wydarzenia_has_Pracownicy_Wydarzenia`
    FOREIGN KEY (`Wydarzenia_idWydarzenia`)
    REFERENCES `mydb`.`Wydarzenia` (`idWydarzenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wydarzenia_has_Pracownicy_Pracownicy1`
    FOREIGN KEY (`Pracownicy_idPracownicy`)
    REFERENCES `mydb`.`Pracownicy` (`idPracownicy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
